name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install tools
        run: |
          python -m pip install --upgrade pip pytest
          pip3 install requests
          pip3 install pandas
          pip3 install plotly
          pip3 install eventbrite
          pip3 install predicthq
          pip3 install reverse_geocoder
          pip3 install googlemaps
          pip3 install xlrd==1.2.0
          pip3 install openpyxl


      - name: Test with unittest
        run: |
          python3 -m unittest test.py
